services:
  - type: web
    name: pdf-analyzer-backend
    env: python3
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pdf-analyzer-db
          property: connectionString
      - key: HUGGINGFACE_API_TOKEN
        sync: false

databases:
  - name: ask_your_pdf
    plan: free
    ipAllowList: []